### ISSUE TITLE
THUNDERBOT ISNT SAFE

### ISSUE THREAD

**Issue by pr13260** [Thundergang/thunderuserbot#9]
https://www.github.com/Thundergang/thunderuserbot/tree/master/thunderbot/thunderbotConfig.py
Line 20 
Devs have added themselves as sudo support and even owner . It not only compromise security but also gives then complete acess over our telegram account..

**Comment by pr13260** [comment]
@pr13260 Issue opened by me

**Comment by nandydark** [comment]
Are you fucking retarded or you even don't know what it means.. we never compromised with security.. Don't create fake rumours..

**Comment by pr13260** [comment]
@nandydark You have compromised u dev guys are making urself sudo 

This not only compromise security but also make u powerful 

You guys are taking over people account

**Comment by nandydark** [comment]
https://t.me/thunderuserbotchat/14286 It's proved so stop being a skid.. and you will get honour to be in the wall of shame as you tried to spread rumous..
